In [4]:
#Importar nuestra librería creada
import SebisDef as seb
import pandas as pd

In [ ]:
#Esta función nos permite leer el archivo que queramos, en este caso será un excel
mallorca=seb.leer_leSebis("Mallorca.xlsx")
mallorca.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16867 entries, 0 to 16866
Data columns (total 50 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              16867 non-null  int64
 1   scrape_id                       16867 non-null  int64
 2   last_scraped                    16867 non-null  datetime64[ns]
 3   source                          16867 non-null  object
 4   name                            16867 non-null  object
 5   host_id                         16867 non-null  int64
 6   host_name                       16867 non-null  object
 7   host_since                      16867 non-null  datetime64[ns]
 8   host_location                   12340 non-null  object
 9   host_response_time              15434 non-null  object
 10  host_response_rate              15434 non-null  float64
 11  host_acceptance_rate            16205 non-null  float64
 12  host_is_superhost               16686 non-null  object
 13  host_listings_count             16867 non-null  int64
 14  host_total_listings_count       16867 non-null  int64
 15  host_verifications              16867 non-null  object
 16  host_has_profile_pic            16867 non-null  object
 17  host_identity_verified          16867 non-null  object
 18  neighbourhood                   6401 non-null   object
 19  neighbourhood_cleansed          16867 non-null  object
 20  neighbourhood_group_cleansed    0 non-null      float64
 21  latitude                        16867 non-null  float64
 22  longitude                       16867 non-null  float64
 23  property_type                   16867 non-null  object
 24  room_type                       16867 non-null  object
 25  accommodates                    16867 non-null  int64
 26  bathrooms                       15923 non-null  float64
 27  bedrooms                        16789 non-null  float64
 28  beds                            15907 non-null  float64
 29  price                           15928 non-null  float64
 30  has_availability                16786 non-null  object
 31  availability_30                 16867 non-null  int64
 32  availability_60                 16867 non-null  int64
 33  availability_90                 16867 non-null  int64
 34  availability_365                16867 non-null  int64
 35  calendar_last_scraped           16867 non-null  datetime64[ns]
 36  number_of_reviews               16867 non-null  int64
 37  number_of_reviews_ltm           16867 non-null  int64
 38  number_of_reviews_l30d          16867 non-null  int64
 39  first_review                    13078 non-null  datetime64[ns]
 40  last_review                     13078 non-null  datetime64[ns]
 41  review_scores_rating            13078 non-null  float64
 42  review_scores_accuracy          13078 non-null  float64
 43  review_scores_cleanliness       13078 non-null  float64
 44  review_scores_checkin           13078 non-null  float64
 45  review_scores_communication     13078 non-null  float64
 46  review_scores_location          13078 non-null  float64
 47  review_scores_value             13078 non-null  float64
 48  instant_bookable                16867 non-null  object
 49  calculated_host_listings_count  16867 non-null  int64
dtypes: datetime64[ns](5), float64(16), int64(14), object(15)
memory usage: 6.4+ MB

In [ ]:
#Con esta función se pueden sustituir los valores nulos con el método "ffill"
mallorca_fili=seb.filiFili(mallorca)
mallorca_fili

/Users/personal/Desktop/Curso Alfredo/3.Valores Nulos/SebisDef.py:26: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  ffili = df.fillna(method="ffill")

,id,scrape_id,last_scraped,source,name,host_id,host_name,host_since,host_location,host_response_time,...,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count
0,69998,20241214212418,2024-12-15,city scrape,COZY HIDEAWAY LOFT... MI AMOR...,353156,Lor,2011-01-19,"Palma, Spain",within an hour,...,2024-10-26,4.95,4.92,4.93,4.95,4.97,4.89,4.81,t,2
1,106833,20241214212418,2024-12-15,city scrape,Villa with a big pool in Mallorca,551974,Xisco,2011-05-02,"Palma de Mallorca, Spain",within an hour,...,2024-09-11,4.89,4.81,4.81,4.89,4.92,4.52,4.63,f,1
2,159218,20241214212418,2024-12-15,city scrape,Farmhouse in Nature -ET-3025,763897,Gabriel,2011-06-30,"Inca, Spain",within an hour,...,2024-10-27,4.92,4.88,4.93,4.96,4.95,4.82,4.75,f,1
3,164185,20241214212418,2024-12-15,city scrape,Corazón de Palma-Habitación con baño privado.,788123,Maria,2011-07-07,"Costa d'en Blanes, Spain",within an hour,...,2024-10-26,4.75,4.72,4.64,4.93,4.90,4.93,4.68,f,1
4,166820,20241214212418,2024-12-15,city scrape,Guest House with Great sea views - Principal Room,794829,Toni,2011-07-08,"Balearic Islands, Spain",within an hour,...,2024-10-08,4.67,4.75,4.35,4.87,4.91,4.94,4.60,t,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16862,1308224357787269888,20241214212418,2024-12-15,city scrape,Very Cosy and very central,588497055,Martina,2024-07-09,"Palma, Spain",within an hour,...,2024-12-06,5.00,5.00,5.00,5.00,5.00,5.00,5.00,f,1
16863,1308461808126489088,20241214212418,2024-12-15,city scrape,Habitación 5,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,2024-12-06,5.00,5.00,5.00,5.00,5.00,5.00,5.00,t,83
16864,1308461814550170880,20241214212418,2024-12-15,city scrape,Habitación 4,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,2024-12-06,5.00,5.00,5.00,5.00,5.00,5.00,5.00,t,83
16865,1308461822310863872,20241214212418,2024-12-15,city scrape,Habitación 3,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,2024-12-06,5.00,5.00,5.00,5.00,5.00,5.00,5.00,t,83
16866,1308461864517467904,20241214212418,2024-12-15,city scrape,Apartamento,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,2024-12-06,5.00,5.00,5.00,5.00,5.00,5.00,5.00,t,83

In [ ]:
#Con esta función se pueden sustituir los valores nulos con el método "bfill"
mallorca_batu=seb.batuFili(mallorca)
mallorca_batu

/Users/personal/Desktop/Curso Alfredo/3.Valores Nulos/SebisDef.py:27: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  batu=df.fillna(method="bfill")

,id,scrape_id,last_scraped,source,name,host_id,host_name,host_since,host_location,host_response_time,...,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count
0,69998,20241214212418,2024-12-15,city scrape,COZY HIDEAWAY LOFT... MI AMOR...,353156,Lor,2011-01-19,"Palma, Spain",within an hour,...,2024-10-26,4.95,4.92,4.93,4.95,4.97,4.89,4.81,t,2
1,106833,20241214212418,2024-12-15,city scrape,Villa with a big pool in Mallorca,551974,Xisco,2011-05-02,"Palma de Mallorca, Spain",within an hour,...,2024-09-11,4.89,4.81,4.81,4.89,4.92,4.52,4.63,f,1
2,159218,20241214212418,2024-12-15,city scrape,Farmhouse in Nature -ET-3025,763897,Gabriel,2011-06-30,"Inca, Spain",within an hour,...,2024-10-27,4.92,4.88,4.93,4.96,4.95,4.82,4.75,f,1
3,164185,20241214212418,2024-12-15,city scrape,Corazón de Palma-Habitación con baño privado.,788123,Maria,2011-07-07,"Costa d'en Blanes, Spain",within an hour,...,2024-10-26,4.75,4.72,4.64,4.93,4.90,4.93,4.68,f,1
4,166820,20241214212418,2024-12-15,city scrape,Guest House with Great sea views - Principal Room,794829,Toni,2011-07-08,"Balearic Islands, Spain",within an hour,...,2024-10-08,4.67,4.75,4.35,4.87,4.91,4.94,4.60,t,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16862,1308224357787269888,20241214212418,2024-12-15,city scrape,Very Cosy and very central,588497055,Martina,2024-07-09,"Palma, Spain",within an hour,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,f,1
16863,1308461808126489088,20241214212418,2024-12-15,city scrape,Habitación 5,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,83
16864,1308461814550170880,20241214212418,2024-12-15,city scrape,Habitación 4,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,83
16865,1308461822310863872,20241214212418,2024-12-15,city scrape,Habitación 3,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,83
16866,1308461864517467904,20241214212418,2024-12-15,city scrape,Apartamento,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,NaT,NaN,NaN,NaN,NaN,NaN,NaN,NaN,t,83

In [ ]:
#Con esta función se pueden sustituir los valores nulos un string en concreto
mallorca_gong=seb.stringong(mallorca)
mallorca_gong

,id,scrape_id,last_scraped,source,name,host_id,host_name,host_since,host_location,host_response_time,...,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count
0,69998,20241214212418,2024-12-15,city scrape,COZY HIDEAWAY LOFT... MI AMOR...,353156,Lor,2011-01-19,"Palma, Spain",within an hour,...,2024-10-26 00:00:00,4.95,4.92,4.93,4.95,4.97,4.89,4.81,t,2
1,106833,20241214212418,2024-12-15,city scrape,Villa with a big pool in Mallorca,551974,Xisco,2011-05-02,"Palma de Mallorca, Spain",ValoritoNulo,...,2024-09-11 00:00:00,4.89,4.81,4.81,4.89,4.92,4.52,4.63,f,1
2,159218,20241214212418,2024-12-15,city scrape,Farmhouse in Nature -ET-3025,763897,Gabriel,2011-06-30,"Inca, Spain",within an hour,...,2024-10-27 00:00:00,4.92,4.88,4.93,4.96,4.95,4.82,4.75,f,1
3,164185,20241214212418,2024-12-15,city scrape,Corazón de Palma-Habitación con baño privado.,788123,Maria,2011-07-07,"Costa d'en Blanes, Spain",within an hour,...,2024-10-26 00:00:00,4.75,4.72,4.64,4.93,4.9,4.93,4.68,f,1
4,166820,20241214212418,2024-12-15,city scrape,Guest House with Great sea views - Principal Room,794829,Toni,2011-07-08,"Balearic Islands, Spain",within an hour,...,2024-10-08 00:00:00,4.67,4.75,4.35,4.87,4.91,4.94,4.6,t,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16862,1308224357787269888,20241214212418,2024-12-15,city scrape,Very Cosy and very central,588497055,Martina,2024-07-09,"Palma, Spain",within an hour,...,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,f,1
16863,1308461808126489088,20241214212418,2024-12-15,city scrape,Habitación 5,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,t,83
16864,1308461814550170880,20241214212418,2024-12-15,city scrape,Habitación 4,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,t,83
16865,1308461822310863872,20241214212418,2024-12-15,city scrape,Habitación 3,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,t,83
16866,1308461864517467904,20241214212418,2024-12-15,city scrape,Apartamento,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,ValoritoNulo,t,83

In [ ]:
mallorca_cuanti_nulos = mallorca.select_dtypes(include=["float64","int64","float","int"])
mallorca_cuali = mallorca.select_dtypes(include=["object","datetime","category"])
#Con esta función se pueden sustituir los valores nulos con el promedio de los valores
mallorca_cuanti = seb.meaniapolis(mallorca_cuanti_nulos)
mallorca_meani = pd.concat([mallorca_cuanti,mallorca_cuali],axis=1)
mallorca_meani

,id,scrape_id,host_id,host_response_rate,host_acceptance_rate,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,...,host_identity_verified,neighbourhood,neighbourhood_cleansed,property_type,room_type,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,69998,20241214212418,353156,1.0,0.91,2,5,NaN,39.569870,2.654640,...,t,"Palma de Mallorca, Balearic Islands, Spain",Palma de Mallorca,Entire loft,Entire home/apt,t,2024-12-15,2012-01-24,2024-10-26,t
1,106833,20241214212418,551974,1.0,0.88,1,1,NaN,39.614580,3.301000,...,t,NaN,Sant Llorenç des Cardassar,Entire villa,Entire home/apt,t,2024-12-15,2012-06-05,2024-09-11,f
2,159218,20241214212418,763897,1.0,1.00,1,1,NaN,39.738390,2.897450,...,t,"Selva, Balearic Islands, Spain",Selva,Entire cottage,Entire home/apt,t,2024-12-15,2011-09-15,2024-10-27,f
3,164185,20241214212418,788123,1.0,0.99,2,3,NaN,39.572710,2.644480,...,t,"Palma de Mallorca, Balearic Islands, Spain",Palma de Mallorca,Private room in guest suite,Private room,t,2024-12-15,2011-08-16,2024-10-26,f
4,166820,20241214212418,794829,1.0,1.00,4,5,NaN,39.678940,2.500520,...,t,NaN,Banyalbufar,Private room in home,Private room,t,2024-12-15,2011-08-08,2024-10-08,t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16862,1308224357787269888,20241214212418,588497055,1.0,1.00,1,1,NaN,39.573649,2.648082,...,t,NaN,Palma de Mallorca,Private room in condo,Private room,t,2024-12-15,NaT,NaT,f
16863,1308461808126489088,20241214212418,587006009,1.0,0.99,1002,1152,NaN,39.607365,2.556080,...,t,NaN,Puigpunyent,Private room in villa,Private room,t,2024-12-15,NaT,NaT,t
16864,1308461814550170880,20241214212418,587006009,1.0,0.99,1002,1152,NaN,39.607365,2.556080,...,t,NaN,Puigpunyent,Private room in villa,Private room,t,2024-12-15,NaT,NaT,t
16865,1308461822310863872,20241214212418,587006009,1.0,0.99,1002,1152,NaN,39.607365,2.556080,...,t,NaN,Puigpunyent,Private room in villa,Private room,t,2024-12-15,NaT,NaT,t
16866,1308461864517467904,20241214212418,587006009,1.0,0.99,1002,1152,NaN,39.607365,2.556080,...,t,NaN,Puigpunyent,Entire rental unit,Entire home/apt,t,2024-12-15,NaT,NaT,t

In [ ]:
#Con esta función se pueden sustituir los valores nulos con la media de los valores
mallorca_cuanti = seb.mediandina(mallorca_cuanti_nulos)
mallorca_medina = pd.concat([mallorca_cuanti,mallorca_cuali],axis=1)
mallorca_medina

,id,scrape_id,host_id,host_response_rate,host_acceptance_rate,host_listings_count,host_total_listings_count,neighbourhood_group_cleansed,latitude,longitude,...,host_identity_verified,neighbourhood,neighbourhood_cleansed,property_type,room_type,has_availability,calendar_last_scraped,first_review,last_review,instant_bookable
0,69998,20241214212418,353156,1.0,0.91,2,5,NaN,39.569870,2.654640,...,t,"Palma de Mallorca, Balearic Islands, Spain",Palma de Mallorca,Entire loft,Entire home/apt,t,2024-12-15,2012-01-24,2024-10-26,t
1,106833,20241214212418,551974,1.0,0.88,1,1,NaN,39.614580,3.301000,...,t,NaN,Sant Llorenç des Cardassar,Entire villa,Entire home/apt,t,2024-12-15,2012-06-05,2024-09-11,f
2,159218,20241214212418,763897,1.0,1.00,1,1,NaN,39.738390,2.897450,...,t,"Selva, Balearic Islands, Spain",Selva,Entire cottage,Entire home/apt,t,2024-12-15,2011-09-15,2024-10-27,f
3,164185,20241214212418,788123,1.0,0.99,2,3,NaN,39.572710,2.644480,...,t,"Palma de Mallorca, Balearic Islands, Spain",Palma de Mallorca,Private room in guest suite,Private room,t,2024-12-15,2011-08-16,2024-10-26,f
4,166820,20241214212418,794829,1.0,1.00,4,5,NaN,39.678940,2.500520,...,t,NaN,Banyalbufar,Private room in home,Private room,t,2024-12-15,2011-08-08,2024-10-08,t
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16862,1308224357787269888,20241214212418,588497055,1.0,1.00,1,1,NaN,39.573649,2.648082,...,t,NaN,Palma de Mallorca,Private room in condo,Private room,t,2024-12-15,NaT,NaT,f
16863,1308461808126489088,20241214212418,587006009,1.0,0.99,1002,1152,NaN,39.607365,2.556080,...,t,NaN,Puigpunyent,Private room in villa,Private room,t,2024-12-15,NaT,NaT,t
16864,1308461814550170880,20241214212418,587006009,1.0,0.99,1002,1152,NaN,39.607365,2.556080,...,t,NaN,Puigpunyent,Private room in villa,Private room,t,2024-12-15,NaT,NaT,t
16865,1308461822310863872,20241214212418,587006009,1.0,0.99,1002,1152,NaN,39.607365,2.556080,...,t,NaN,Puigpunyent,Private room in villa,Private room,t,2024-12-15,NaT,NaT,t
16866,1308461864517467904,20241214212418,587006009,1.0,0.99,1002,1152,NaN,39.607365,2.556080,...,t,NaN,Puigpunyent,Entire rental unit,Entire home/apt,t,2024-12-15,NaT,NaT,t

In [ ]:
#Con esta función se pueden sustituir los valores nulos con un número constante
mallorca_constant=seb.constantinopla(mallorca)
mallorca_constant

,id,scrape_id,last_scraped,source,name,host_id,host_name,host_since,host_location,host_response_time,...,last_review,review_scores_rating,review_scores_accuracy,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,calculated_host_listings_count
0,69998,20241214212418,2024-12-15,city scrape,COZY HIDEAWAY LOFT... MI AMOR...,353156,Lor,2011-01-19,"Palma, Spain",within an hour,...,2024-10-26 00:00:00,4.95,4.92,4.93,4.95,4.97,4.89,4.81,t,2
1,106833,20241214212418,2024-12-15,city scrape,Villa with a big pool in Mallorca,551974,Xisco,2011-05-02,"Palma de Mallorca, Spain",0,...,2024-09-11 00:00:00,4.89,4.81,4.81,4.89,4.92,4.52,4.63,f,1
2,159218,20241214212418,2024-12-15,city scrape,Farmhouse in Nature -ET-3025,763897,Gabriel,2011-06-30,"Inca, Spain",within an hour,...,2024-10-27 00:00:00,4.92,4.88,4.93,4.96,4.95,4.82,4.75,f,1
3,164185,20241214212418,2024-12-15,city scrape,Corazón de Palma-Habitación con baño privado.,788123,Maria,2011-07-07,"Costa d'en Blanes, Spain",within an hour,...,2024-10-26 00:00:00,4.75,4.72,4.64,4.93,4.90,4.93,4.68,f,1
4,166820,20241214212418,2024-12-15,city scrape,Guest House with Great sea views - Principal Room,794829,Toni,2011-07-08,"Balearic Islands, Spain",within an hour,...,2024-10-08 00:00:00,4.67,4.75,4.35,4.87,4.91,4.94,4.60,t,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16862,1308224357787269888,20241214212418,2024-12-15,city scrape,Very Cosy and very central,588497055,Martina,2024-07-09,"Palma, Spain",within an hour,...,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,f,1
16863,1308461808126489088,20241214212418,2024-12-15,city scrape,Habitación 5,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,t,83
16864,1308461814550170880,20241214212418,2024-12-15,city scrape,Habitación 4,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,t,83
16865,1308461822310863872,20241214212418,2024-12-15,city scrape,Habitación 3,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,t,83
16866,1308461864517467904,20241214212418,2024-12-15,city scrape,Apartamento,587006009,Holidu,2024-07-02,"Palma, Spain",within an hour,...,0,0.00,0.00,0.00,0.00,0.00,0.00,0.00,t,83

In [ ]:
#Con esta función podemos contar cuántos valores nulos hay en nuestro archivo
cuenta_nulos_mallorca=seb.valoritosnulos(mallorca)
cuenta_nulos_mallorca

id                                    0
scrape_id                             0
last_scraped                          0
source                                0
name                                  0
host_id                               0
host_name                             0
host_since                            0
host_location                      4527
host_response_time                 1433
host_response_rate                 1433
host_acceptance_rate                662
host_is_superhost                   181
host_listings_count                   0
host_total_listings_count             0
host_verifications                    0
host_has_profile_pic                  0
host_identity_verified                0
neighbourhood                     10466
neighbourhood_cleansed                0
neighbourhood_group_cleansed      16867
latitude                              0
longitude                             0
property_type                         0
room_type                             0
accommodates                          0
bathrooms                           944
bedrooms                             78
beds                                960
price                               939
has_availability                     81
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
calendar_last_scraped                 0
number_of_reviews                     0
number_of_reviews_ltm                 0
number_of_reviews_l30d                0
first_review                       3789
last_review                        3789
review_scores_rating               3789
review_scores_accuracy             3789
review_scores_cleanliness          3789
review_scores_checkin              3789
review_scores_communication        3789
review_scores_location             3789
review_scores_value                3789
instant_bookable                      0
calculated_host_listings_count        0
dtype: int64
72672

In [20]:
cuenta_nulos_fili=seb.valoritosnulos(mallorca_fili)
cuenta_nulos_fili

id                                    0
scrape_id                             0
last_scraped                          0
source                                0
name                                  0
host_id                               0
host_name                             0
host_since                            0
host_location                         0
host_response_time                    0
host_response_rate                    0
host_acceptance_rate                  0
host_is_superhost                     0
host_listings_count                   0
host_total_listings_count             0
host_verifications                    0
host_has_profile_pic                  0
host_identity_verified                0
neighbourhood                         0
neighbourhood_cleansed                0
neighbourhood_group_cleansed      16867
latitude                              0
longitude                             0
property_type                         0
room_type                             0
accommodates                          0
bathrooms                             0
bedrooms                              0
beds                                  0
price                                 0
has_availability                      0
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
calendar_last_scraped                 0
number_of_reviews                     0
number_of_reviews_ltm                 0
number_of_reviews_l30d                0
first_review                          0
last_review                           0
review_scores_rating                  0
review_scores_accuracy                0
review_scores_cleanliness             0
review_scores_checkin                 0
review_scores_communication           0
review_scores_location                0
review_scores_value                   0
instant_bookable                      0
calculated_host_listings_count        0
dtype: int64
16867

In [21]:
cuenta_nulos_medina=seb.valoritosnulos(mallorca_medina)
cuenta_nulos_medina

id                                    0
scrape_id                             0
host_id                               0
host_response_rate                    0
host_acceptance_rate                  0
host_listings_count                   0
host_total_listings_count             0
neighbourhood_group_cleansed      16867
latitude                              0
longitude                             0
accommodates                          0
bathrooms                             0
bedrooms                              0
beds                                  0
price                                 0
availability_30                       0
availability_60                       0
availability_90                       0
availability_365                      0
number_of_reviews                     0
number_of_reviews_ltm                 0
number_of_reviews_l30d                0
review_scores_rating                  0
review_scores_accuracy                0
review_scores_cleanliness             0
review_scores_checkin                 0
review_scores_communication           0
review_scores_location                0
review_scores_value                   0
calculated_host_listings_count        0
last_scraped                          0
source                                0
name                                  0
host_name                             0
host_since                            0
host_location                      4527
host_response_time                 1433
host_is_superhost                   181
host_verifications                    0
host_has_profile_pic                  0
host_identity_verified                0
neighbourhood                     10466
neighbourhood_cleansed                0
property_type                         0
room_type                             0
has_availability                     81
calendar_last_scraped                 0
first_review                       3789
last_review                        3789
instant_bookable                      0
dtype: int64
41133

In [22]:
cuenta_nulos_constant=seb.valoritosnulos(mallorca_constant)
cuenta_nulos_constant

id                                0
scrape_id                         0
last_scraped                      0
source                            0
name                              0
host_id                           0
host_name                         0
host_since                        0
host_location                     0
host_response_time                0
host_response_rate                0
host_acceptance_rate              0
host_is_superhost                 0
host_listings_count               0
host_total_listings_count         0
host_verifications                0
host_has_profile_pic              0
host_identity_verified            0
neighbourhood                     0
neighbourhood_cleansed            0
neighbourhood_group_cleansed      0
latitude                          0
longitude                         0
property_type                     0
room_type                         0
accommodates                      0
bathrooms                         0
bedrooms                          0
beds                              0
price                             0
has_availability                  0
availability_30                   0
availability_60                   0
availability_90                   0
availability_365                  0
calendar_last_scraped             0
number_of_reviews                 0
number_of_reviews_ltm             0
number_of_reviews_l30d            0
first_review                      0
last_review                       0
review_scores_rating              0
review_scores_accuracy            0
review_scores_cleanliness         0
review_scores_checkin             0
review_scores_communication       0
review_scores_location            0
review_scores_value               0
instant_bookable                  0
calculated_host_listings_count    0
dtype: int64
0